version: '2'
services:

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - mysql
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
			- ./logs/nginx/:/var/log/nginx
    volumes_from:
      - code

  php:
    build: .
    working_dir: /var/www
    volumes_from:
      - code

  mysql:
    image: mysql
    ports:
      - "33061:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
    - '8181:80'

  code:
    image: busybox
    volumes:
      - ./www:/var/www
